"""Re-render every paper figure in the unified theme (ivsh.viz), from saved
data + cached banks -- no slow pipeline recompute, no number changes.

Covers the older pipeline figures (synthetic cvar_comparison/cvar_ci/
pnl_distributions/architecture; real cumulative_pnl/activation_timeline) and the
analysis figures (multiverse/multiseed/walkforward). The hero + graphical-abstract
figures are regenerated by re-running their own (now themed) scripts.

    python scripts/restyle_figures.py
"""

from __future__ import annotations

import sys as _sys
import pathlib as _pl

_sys.path.insert(0, str(_pl.Path(__file__).resolve().parents[1] / "src"))
try:
    _sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

import pickle
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

from ivsh.evaluation import report as R
from ivsh.training.train import TrainConfig, fit_prototype, make_standardizer
from ivsh.utils.splits import chronological_split, subset
from ivsh.viz import METHOD_COLORS, apply_theme

apply_theme()
ROOT = _pl.Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
METHODS_MAIN = ["delta", "delta_vega", "blackbox", "prototype"]


def _pnl_by_method(df, methods):
    return {m: df[f"pnl_{m}"].to_numpy() for m in methods if f"pnl_{m}" in df}


def synthetic():
    figs = ROOT / "reports" / "figures"; tab = ROOT / "reports" / "tables"
    R.plot_architecture(figs / "architecture.png")
    mc = pd.read_csv(tab / "model_comparison.csv").set_index("method")
    metrics = {m: {"cvar_95": mc.loc[m, "cvar_95"], "cvar_99": mc.loc[m, "cvar_99"]}
               for m in mc.index}
    R.plot_cvar_comparison(metrics, figs / "cvar_comparison.png")
    paths = pd.read_csv(tab / "test_pnl_paths.csv")
    pbm = _pnl_by_method(paths, ["unhedged"] + METHODS_MAIN)
    R.plot_pnl_distributions(pbm, figs / "pnl_distributions.png")
    R.plot_cvar_ci({m: pbm[m] for m in METHODS_MAIN if m in pbm}, figs / "cvar_ci.png")
    print("  synthetic: architecture, cvar_comparison, cvar_ci, pnl_distributions")


def real_pipeline_figs():
    figs = ROOT / "reports_real" / "figures"; tab = ROOT / "reports_real" / "tables"
    paths = pd.read_csv(tab / "test_pnl_paths.csv")
    order = np.argsort(paths["start_day"].to_numpy())
    dates = pd.to_datetime(paths["date"]).to_numpy() if "date" in paths else None
    pbm = _pnl_by_method(paths, METHODS_MAIN)
    R.plot_cumulative_pnl(pbm, order, dates, figs / "cumulative_pnl.png")
    # activation timeline: refit the base prototype on the cached SPY bank
    with open(ART / "bank_spy.pkl", "rb") as f:
        d = pickle.load(f); bank, years = d["bank"], d["years"]
    sp = chronological_split(bank)
    trb, vlb, teb = subset(bank, sp.train), subset(bank, sp.val), subset(bank, sp.test)
    scaler = make_standardizer(trb)
    proto, _, _ = fit_prototype(trb, scaler, TrainConfig(n_prototypes=8, l2=1e-3, max_iter=250,
                                anchor=True, action_scale=1.5, seed=7), val_bank=vlb)
    x = scaler.transform(teb.flat_features())
    w = proto.weights(x).reshape(teb.n_episodes, teb.horizon, -1).mean(axis=1)  # [E,K]
    order_t = np.argsort(teb.start_days)
    yrs = years[sp.test]
    R.plot_activation_timeline(w, order_t, teb.regime_start, yrs, figs / "activation_timeline.png")
    print("  real: cumulative_pnl, activation_timeline")


def _grouped_bar(csv, figpath, title):
    df = pd.read_csv(csv)
    unis = list(dict.fromkeys(df["universe"]))
    methods = [m for m in ["delta", "delta_vega", "blackbox", "prototype", "ppo", "sac"]
               if m in set(df["method"])]
    x = np.arange(len(unis)); bw = 0.8 / max(len(methods), 1)
    fig, ax = plt.subplots(figsize=(2.2 * len(unis) + 4, 4.5))
    piv = df.pivot_table(index="universe", columns="method", values="cvar_95")
    for i, m in enumerate(methods):
        ax.bar(x + i * bw, [piv.loc[u, m] for u in unis], bw, label=m,
               color=METHOD_COLORS.get(m), edgecolor="k", linewidth=0.4)
    ax.set_xticks(x + bw * (len(methods) - 1) / 2); ax.set_xticklabels([u.upper() for u in unis])
    ax.set_ylabel("CVaR95 tail loss (test split)"); ax.set_title(title)
    ax.legend(fontsize=8, ncol=2)
    fig.tight_layout(); fig.savefig(figpath, dpi=140); plt.close(fig)


def analysis():
    figs = ROOT / "reports_real" / "figures"; tab = ROOT / "reports_real" / "tables"
    _grouped_bar(tab / "multiverse_comparison.csv", figs / "multiverse_cvar.png",
                 "Multi-universe hedging comparison")
    # multiseed bar
    ms = pd.read_csv(tab / "multiseed_cvar.csv", index_col=0)
    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    ax.bar(ms.index, ms["cvar95_mean"], yerr=ms["cvar95_std"], capsize=5,
           color=[METHOD_COLORS.get(m) for m in ms.index], edgecolor="k", linewidth=0.5)
    ax.set_ylabel("CVaR95 (mean +/- std over seeds)"); ax.set_title("Multi-seed robustness")
    fig.tight_layout(); fig.savefig(figs / "multiseed_cvar.png", dpi=140); plt.close(fig)
    # walk-forward lines (SPY + QQQ)
    for csv, suf in [("walkforward_cvar.csv", ""), ("walkforward_cvar_qqq.csv", "_qqq")]:
        p = tab / csv
        if not p.exists():
            continue
        df = pd.read_csv(p).set_index("test_year")
        fig, ax = plt.subplots(figsize=(8.5, 4.5))
        for m in [c for c in ["delta", "delta_vega", "blackbox", "prototype", "prototype_capped", "ppo"] if c in df]:
            ax.plot(df.index, df[m], marker="o", label=m, color=METHOD_COLORS.get(m.replace("_capped", "")))
        ax.set_ylabel("CVaR95 tail loss"); ax.set_xlabel("test year (train = all prior years)")
        ax.set_title(f"Walk-forward CVaR95 by year{(' - ' + suf[1:]) if suf else ''}")
        ax.legend(fontsize=8); fig.tight_layout()
        fig.savefig(figs / f"walkforward_cvar{suf}.png", dpi=140); plt.close(fig)
    print("  analysis: multiverse_cvar, multiseed_cvar, walkforward(+qqq)")


def main():
    for name, fn in [("synthetic", synthetic), ("real_pipeline", real_pipeline_figs),
                     ("analysis", analysis)]:
        try:
            fn()
        except Exception as e:
            print(f"  FAILED {name}: {e!r}")
    print("restyle done")


if __name__ == "__main__":
    main()
